# Generated by Django 4.2.6 on 2023-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehook', '0003_alter_customerbrokers_broker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbrokers',
            name='broker_secret_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
