# Generated by Django 4.2.6 on 2024-03-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehook', '0004_alter_customerbrokers_broker_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbrokers',
            name='broker_name',
            field=models.CharField(choices=[('Alpaca', 'Alpaca'), ('Alpaca - Paper', 'Alpaca-Paper')], max_length=255),
        ),
        migrations.AlterField(
            model_name='customerbrokers',
            name='broker_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
