# Generated by Django 4.2.6 on 2024-03-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradehook', '0005_alter_customerbrokers_broker_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbrokers',
            name='broker_name',
            field=models.CharField(choices=[('Alpaca', 'Alpaca'), ('Alpaca - Paper', 'Alpaca - Paper')], max_length=255),
        ),
    ]
